# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rl_gym',
                'doc_host': 'https://Revys17.github.io',
                'git_url': 'https://github.com/Revys17/rl_gym',
                'lib_path': 'rl_gym'},
  'syms': {'rl_gym.core': {'rl_gym.core.foo': ('core.html#foo', 'rl_gym/core.py')}}}
